services:
  db:
    image: postgres:15
    container_name: mini-library-db
    restart: always
    environment:
      POSTGRES_USER: odium
      POSTGRES_DB: test_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odium -d test_db"]
      interval: 2s
      timeout: 5s
      retries: 10

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-library-migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://odium@db:5432/test_db
    command: alembic upgrade head

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-library-seed-admin
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql+psycopg2://odium@db:5432/test_db
    command: python -m app.seed

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-library-api
    restart: always
    depends_on:
      seed:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql+psycopg2://odium@db:5432/test_db
      DEBUG: "True"
      PROJECT_NAME: "FastAPI Library"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

volumes:
  pgdata:
